// <auto-generated />
using BlueHarbor.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueHarbor.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715133322_CleanupRedundantIndexDeclaration")]
    partial class CleanupRedundantIndexDeclaration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("BlueHarbor.API.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BerthId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShipId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.HasIndex("BerthId", "StartDay", "EndDay")
                        .IsUnique()
                        .HasDatabaseName("UX_Assignments_BerthId_StartDay_EndDay");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("BlueHarbor.API.Models.Berth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Berths");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "XL-1",
                            Size = "XL"
                        },
                        new
                        {
                            Id = 2,
                            Name = "L-1",
                            Size = "L"
                        },
                        new
                        {
                            Id = 3,
                            Name = "M-1",
                            Size = "M"
                        },
                        new
                        {
                            Id = 4,
                            Name = "M-2",
                            Size = "M"
                        },
                        new
                        {
                            Id = 5,
                            Name = "S-1",
                            Size = "S"
                        },
                        new
                        {
                            Id = 6,
                            Name = "S-2",
                            Size = "S"
                        },
                        new
                        {
                            Id = 7,
                            Name = "S-3",
                            Size = "S"
                        },
                        new
                        {
                            Id = 8,
                            Name = "S-4",
                            Size = "S"
                        });
                });

            modelBuilder.Entity("BlueHarbor.API.Models.PortLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArrivalDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartureDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PortLogs");
                });

            modelBuilder.Entity("BlueHarbor.API.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArrivalDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OccupationDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("BlueHarbor.API.Models.SystemState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SystemStates");
                });

            modelBuilder.Entity("BlueHarbor.API.Models.Assignment", b =>
                {
                    b.HasOne("BlueHarbor.API.Models.Berth", "Berth")
                        .WithMany()
                        .HasForeignKey("BerthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlueHarbor.API.Models.Ship", "Ship")
                        .WithMany()
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Berth");

                    b.Navigation("Ship");
                });
#pragma warning restore 612, 618
        }
    }
}
